/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./index.njk",
    "./src/**/*.{js,ts,jsx,tsx,css}",
    "./src/**/*.{njk,md}",
    "./src/**/*.svg",
    "./_site/**/*.{html,js}",
    "./_includes/**/*.{html,njk}",
    "./participants/**/*.{md}",
    "./assets/**/*.{css,js}",
    "./**/*.njk"
  ],
  safelist: [
    'bg-gray-50',
    'min-h-screen',
    'flex',
    'flex-col',
    'container',
    'mx-auto',
    'px-4',
    'py-8',
    'text-4xl',
    'font-bold',
    'text-center',
    'mb-8',
    'max-w-3xl',
    'text-lg',
    'text-gray-600',
    'mb-12',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'gap-8',
    'w-24',
    'h-24',
    'rounded-full',
    'mb-4',
    'object-cover',
    'text-xl',
    'font-semibold',
    'mb-2',
    'text-emerald-600',
    'font-medium',
    'text-left',
    'transition-all',
    'duration-500',
    'ease-in-out',
    'h-10',
    'space-x-4',
    'space-x-8',
    'bg-white',
    'shadow-sm',
    'justify-between',
    'items-center',
    'text-gray-800',
    'bg-gray-900',
    'text-white',
    'mt-auto',
    'transition-colors',
    'duration-300',
    'inline-flex',
    'w-5',
    'h-5',
    'mr-2'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}